Change pipeline

diff --git a/.github/workflows/build-worker.yaml b/.github/workflows/build-worker.yaml
--- a/.github/workflows/build-worker.yaml
+++ b/.github/workflows/build-worker.yaml
@@ -1,111 +1,110 @@
-name: Worker Image -> GHCR -> update Helm values
+# name: Worker Image -> GHCR -> update Helm values
+# on:
+#   push:
+#     branches: ["master"]
+#     tags: ["v*"]
+#     paths:
+#       - "src/worker/**"
+#       - ".github/workflows/build-worker.yaml"
+#   pull_request:
+#     branches:
+#       - master
+# #      - gitops
+#   workflow_dispatch:
 
-on:
-  push:
-    branches: ["master"]
-    tags: ["v*"]
-    paths:
-      - "src/worker/**"
-      - ".github/workflows/build-worker.yaml"
-  pull_request:
-    branches:
-      - master
-#      - gitops
-  workflow_dispatch:
+# env:
+#   REGISTRY: ghcr.io
+#   SERVICE: worker
+#   IMAGE: ghcr.io/kastoni/kubevote-worker              #ghcr.io/${{ github.repository_owner | toLower }}/KubeVote-vote
+#   PATH_TO_HELM: ./helm/KubeVote
 
-env:
-  REGISTRY: ghcr.io
-  SERVICE: worker
-  IMAGE: ghcr.io/kastoni/kubevote-worker              #ghcr.io/${{ github.repository_owner | toLower }}/KubeVote-vote
-  PATH_TO_HELM: ./helm/KubeVote
+# jobs:
+#   build_push_update:
+#     runs-on: ubuntu-latest
+#     permissions:
+#       contents: write
+#       packages: write
+#       id-token: write
 
-jobs:
-  build_push_update:
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-      packages: write
-      id-token: write
+#     steps:
+#       - uses: actions/checkout@v6.0.1
+#         with:
+#           fetch-depth: 0
+#           ref: master
 
-    steps:
-      - uses: actions/checkout@v6.0.1
-        with:
-          fetch-depth: 0
-          ref: master
+#       - uses: docker/setup-qemu-action@v3.7.0
+#       - uses: docker/setup-buildx-action@v3.12.0
 
-      - uses: docker/setup-qemu-action@v3.7.0
-      - uses: docker/setup-buildx-action@v3.12.0
+#       - name: Login GHCR
+#         uses: docker/login-action@v3.6.0
+#         with:
+#           registry: ${{ env.REGISTRY }}
+#           username: ${{ github.actor }}
+#           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Login GHCR
-        uses: docker/login-action@v3.6.0
-        with:
-          registry: ${{ env.REGISTRY }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+#       - name: Meta tags
+#         id: meta
+#         uses: docker/metadata-action@v5.10.0
+#         with:
+#           images: ${{ env.IMAGE }}
+#           tags: |
+#             type=raw,value=latest
+#             type=sha,format=short
+#             type=sha,format=long
+#             type=semver,pattern={{version}},prefix=v
+#             type=semver,pattern={{major}}.{{minor}},prefix=v
+#             type=semver,pattern={{major}},prefix=v
+#           labels: |
+#             org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
+#             org.opencontainers.image.revision=${{ github.sha }}
+#             org.opencontainers.image.version=${{ steps.meta.outputs.version }}
+#             org.opencontainers.image.created=${{ steps.meta.outputs.created }}
 
-      - name: Meta tags
-        id: meta
-        uses: docker/metadata-action@v5.10.0
-        with:
-          images: ${{ env.IMAGE }}
-          tags: |
-            type=raw,value=latest
-            type=sha,format=short
-            type=sha,format=long
-            type=semver,pattern={{version}},prefix=v
-            type=semver,pattern={{major}}.{{minor}},prefix=v
-            type=semver,pattern={{major}},prefix=v
-          labels: |
-            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
-            org.opencontainers.image.revision=${{ github.sha }}
-            org.opencontainers.image.version=${{ steps.meta.outputs.version }}
-            org.opencontainers.image.created=${{ steps.meta.outputs.created }}
+#       - name: Build & Push
+#         id: build
+#         uses: docker/build-push-action@v6.18.0
+#         with:
+#           context: ./src/${{ env.SERVICE }}
+#           file: ./src/${{ env.SERVICE }}/Dockerfile
+#           platforms: linux/amd64,linux/arm64
+#           push: true
+#           tags: ${{ steps.meta.outputs.tags }}
+#           labels: ${{ steps.meta.outputs.labels }}
+#           cache-from: type=gha,scope=${{ env.SERVICE }}
+#           cache-to: type=gha,mode=max,scope=${{ env.SERVICE }}
+#           sbom: true
+#           provenance: mode=max
 
-      - name: Build & Push
-        id: build
-        uses: docker/build-push-action@v6.18.0
-        with:
-          context: ./src/${{ env.SERVICE }}
-          file: ./src/${{ env.SERVICE }}/Dockerfile
-          platforms: linux/amd64,linux/arm64
-          push: true
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
-          cache-from: type=gha,scope=${{ env.SERVICE }}
-          cache-to: type=gha,mode=max,scope=${{ env.SERVICE }}
-          sbom: true
-          provenance: mode=max
+#       - name: Install yq (pinned)
+#         run: |
+#           YQ_VERSION="v4.50.1"
+#           curl -sSL -o /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
+#           chmod +x /usr/local/bin/yq
+#           yq -V
 
-      - name: Install yq (pinned)
-        run: |
-          YQ_VERSION="v4.50.1"
-          curl -sSL -o /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
-          chmod +x /usr/local/bin/yq
-          yq -V
+#       - name: Update Helm values with digest
+#         env:
+#           DIGEST: ${{ steps.build.outputs.digest }}
+#           IMAGE: ${{ env.IMAGE }}
+#           PATH_TO_HELM: ${{ env.PATH_TO_HELM }}
+#         run: |
+#           # git checkout gitops
+#           cd ${{ env.PATH_TO_HELM}}
+#           # worker.image.repository: ghcr.io/...
+#           # worker.image.digest: sha256:...
+#           yq -i '.${{ env.SERVICE }}.image.repository = strenv(IMAGE)' ./values.yaml
+#           yq -i '.${{ env.SERVICE }}.image.digest = strenv(DIGEST)' ./values.yaml
 
-      - name: Update Helm values with digest
-        env:
-          DIGEST: ${{ steps.build.outputs.digest }}
-          IMAGE: ${{ env.IMAGE }}
-          PATH_TO_HELM: ${{ env.PATH_TO_HELM }}
-        run: |
-          # git checkout gitops
-          cd ${{ env.PATH_TO_HELM}}
-          # worker.image.repository: ghcr.io/...
-          # worker.image.digest: sha256:...
-          yq -i '.${{ env.SERVICE }}.image.repository = strenv(IMAGE)' ./values.yaml
-          yq -i '.${{ env.SERVICE }}.image.digest = strenv(DIGEST)' ./values.yaml
+#           git config user.name "github-actions[bot]"
+#           git config user.email "github-actions[bot]@users.noreply.github.com"
+#           git add ./values.yaml
+#           git commit -m "chore(${{ env.SERVICE }}): bump image to ${IMAGE}@${DIGEST}" || exit 0
 
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
-          git add ./values.yaml
-          git commit -m "chore(${{ env.SERVICE }}): bump image to ${IMAGE}@${DIGEST}" || exit 0
-
-          for i in 1 2 3 4 5; do
-            # git pull --rebase origin gitops
-            # git push origin gitops && break
-            git pull --rebase origin master
-            git push origin master && break
-            echo "Push failed, retrying in 5s..."
-            sleep 5
-          done
+#           for i in 1 2 3 4 5; do
+#             # git pull --rebase origin gitops
+#             # git push origin gitops && break
+#             git pull --rebase origin master
+#             git push origin master && break
+#             echo "Push failed, retrying in 5s..."
+#             sleep 5
+#           done
